@baseUrl = http://localhost:6000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "edu2023",
  "password": "bar2023",
  "email": "bar@gmail.com",
  "avatarColor": "blue"
}

###
POST {{baseUrl}}/{{urlPath}}/signin
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "edu2023",
  "password": "bar2023"
}

###
GET {{baseUrl}}/{{urlPath}}/signout
Content-Type: application/json
Accept: application/json
withCredentials: true
